language: node_js
node_js:
  - "stable"

script:
  -npm install
  -npm run build #
  
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $github _token
  local_dir: build
  on:
  branch: main