language: node_js
node_js:
  - "14"  # Use Node.js 14.x LTS

script:
  - npm install
  - npm run build

deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
